# -*- coding: utf-8 -*-
"""Fifa Football Player Data Analysis .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DKRE4iIIA4OzAzOC66Q5vpovox9aDqH8

#PROJECT NAME : 
##ANALYSIS OF FOOTBALL PLAYER DATA

Analyzed By : [Nischal Khanal](https://www.linkedin.com/in/nischal-khanal-031740230/)

Required libraries:
1. Numpy
2. Pandas
3. Matplot
"""

#importing library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Download dataset & replace with your dataset path
fifa=pd.read_csv("/content/players_20.csv")

# If we print fifa only then all dataset is print
fifa

# For easy to understand we only look top five rows of our dataset
# for that use use "head()" function which print first five row
fifa.head()

# Now we are going to see how many columns with which names in our data set
count=1
for col in fifa.columns:
  print(col)
  count=count+1
print(count)

# In above at last we print the total no of columns which is 105
# So there are many columns where many of them are not needed for us
# At first we analyze that how many playes belongs in which country for that we  use "valu_count()" function
fifa["nationality"].value_counts()

# There are 165 county name but we need only top 5 county with no of player
fifa["nationality"].value_counts()[0:5]

# If I want to print only the name of top country only without no of playes then we use "key()" function
fifa["nationality"].value_counts()[0:5].keys()

# Now we are going to plot the bar plot of the above dataset
plt.figure(figsize=(8,5))
plt.bar(list(fifa["nationality"].value_counts()[0:5].keys()),list(fifa["nationality"].value_counts()[0:5]),color={"k","b","g","y","r"})
plt.show()

# Righ now we have looked the nationality column. Now we are going to look more column to further analysis
# Now we analyse the salary of each player for that we look above list of columns
# where one of them colmn is "wage_eur" which is a salary column
# we print the "wage_eur"(salary) with "short_name" for that
player_salary=fifa[["short_name","wage_eur"]][0:5]
player_salary

# Lets arrange the salary in descending order & print itfor that
player_salary=player_salary.sort_values(by=["wage_eur"],ascending=False)
player_salary

# Bar graph plotting
# For plotting the graph first parameter is "catogorical" & second parameter is numerical
plt.figure(figsize=(8,5))
plt.bar(list(player_salary["short_name"][0:5]),list(player_salary["wage_eur"][0:5]),color={"k","b","g","y","r"})
plt.show()

fifa["nationality"]=="Germany"

# In above output we get a bunch of True & False
# If you got "False which means that particular reacord "nationality" is not "Germany" otherwise if we got True than we know that 
# particular record "nationality" is "Germany"

player_defending=fifa[["short_name","defending","nationality","club"]]

player_defending.sort_values(by=["defending"],ascending=False).head()

# I want to study about only "Madrid Club" player data
real_madrid=player_defending[player_defending["club"]=="Real Madrid"]
real_madrid

# we only want top data
real_madrid=player_defending[player_defending["club"]=="Real Madrid"].head()
real_madrid

# These are the top defending player of the "Real Madrid " club